In [423]:
import numpy as np
from functools import cmp_to_key
import csv
import cv2
import os
import numpy as np
import numpy as ndarray
import tensorflow as tf
import pandas as pd
import xlrd
import collections
import numpy 
import numpy as geek 
import heapq
import heapq
import os
from functools import cmp_to_key

In [426]:
aldata=[]
count=0
with open(r"C:\Users\Student\Desktop\dataset_1\our_data_text_format.csv",'rt')as d:
    data = csv.reader(d, delimiter = ',')
    for row in data:
        #print(row)          # print all elements in the dataset
        count+=1
        aldata.append(row)    
#print(count)                # print total rows in the dataset

#print(row)


In [425]:
#print(aldata)

In [428]:
data1= pd.DataFrame(aldata) 
#print(data1)

In [429]:
data1.shape                            # find the shape of the dataset 

data1.columns                          # find the total columns of the dataset

RangeIndex(start=0, stop=24, step=1)

In [430]:
data1.columns=['q1', 'q2', 'q3', 'q4', 'q5', 'q6','q7','q8','q9','q10','q11','q12','q13','q14','q15','q16','q17','q18','q19','q20','q21','q22','q23','q24']

                                              # change the labels with q1, q2, q3................q24

In [431]:
print(data1 ,type(data1))                

            q1      q2   q3             q4          q5      q6            q7  \
0        URBAN     OBC   NO           CBSE        CBSE  FATHER         OTHER   
1        URBAN     GEN   NO           CBSE  SATE BOARD  FATHER       PRIVATE   
2    SUB URBAN     OBC   NO           CBSE  SATE BOARD  MOTHER          GOVT   
3        RURAL     GEN   NO           CBSE        CBSE  MOTHER         OTHER   
4        URBAN     OBC   NO           CBSE  SATE BOARD  FATHER       PRIVATE   
5        RURAL   SC/ST   NO  STATE  BOARD   SATE BOARD  FATHER         OTHER   
6        RURAL   SC/ST   NO           CBSE  SATE BOARD  FATHER          GOVT   
7        RURAL     OBC   NO  STATE  BOARD   SATE BOARD  FATHER         OTHER   
8        URBAN   SC/ST   NO  STATE  BOARD   SATE BOARD  FATHER          GOVT   
9    SUB URBAN     GEN   NO           ICSE  SATE BOARD  FATHER          GOVT   
10       RURAL     GEN   NO           CBSE        CBSE  FATHER          GOVT   
11   SUB URBAN     GEN   NO           CB

In [432]:
q1 = data1['q1']                                             # print the first column that is "question 1" from the dataset 
print(q1)

0          URBAN
1          URBAN
2      SUB URBAN
3          RURAL
4          URBAN
5          RURAL
6          RURAL
7          RURAL
8          URBAN
9      SUB URBAN
10         RURAL
11     SUB URBAN
12         RURAL
13         URBAN
14         URBAN
15         RURAL
16         RURAL
17         RURAL
18         RURAL
19         URBAN
20         RURAL
21     SUB URBAN
22         RURAL
23         URBAN
24         RURAL
25         RURAL
26         URBAN
27         URBAN
28         URBAN
29         URBAN
         ...    
520        RURAL
521        RURAL
522        URBAN
523    SUB URBAN
524    SUB URBAN
525        URBAN
526        URBAN
527    SUB URBAN
528        URBAN
529        URBAN
530    SUB URBAN
531        RURAL
532        URBAN
533        URBAN
534        URBAN
535        URBAN
536    SUB URBAN
537        URBAN
538        URBAN
539    SUB URBAN
540        RURAL
541        RURAL
542    SUB URBAN
543    SUB URBAN
544        RURAL
545        RURAL
546        RURAL
547        URB

In [433]:
count_q1 = collections.Counter(q1)                                    # count the total frequency of a perticular field
print(count_q1,type(count_q1))


count_q1.items()

Counter({'URBAN': 244, 'RURAL': 195, 'SUB URBAN': 108, 'OTHER': 3}) <class 'collections.Counter'>


dict_items([('URBAN', 244), ('SUB URBAN', 108), ('RURAL', 195), ('OTHER', 3)])

In [434]:
sort_q1 = sorted(count_q1.values(),reverse=True)                     # sort the frequency in reverce order
print(sort_q1)

[244, 195, 108, 3]


In [435]:
a=urban =244                                        # elements with there frequency
b=rural=195
c=sub_urban=108
d=others=3

avg_a= (a/550)                                       # avarge formula 
avg_b= (b/550)
avg_c= (c/550)
avg_d= (d/550)
prob_q1=(avg_a,avg_b,avg_c,avg_d)                   #collect all avarges  results in "prob_q1"
ka=(prob_q1,type(prob_q1))
print(ka)


ha= np.array(prob_q1)                               # convert the tuple with array and print the array
print(ha)

((0.44363636363636366, 0.35454545454545455, 0.19636363636363635, 0.005454545454545455), <class 'tuple'>)
[0.44363636 0.35454545 0.19636364 0.00545455]


In [436]:
sort_q1 = -np.sort(-ha)                                           #sort the array with  "sort_q1" name
#print(sort_q1)

sort_q1_matrix = np.asmatrix(sort_q1)                           # convert the array into matrix  with name "sort_q1_matrix"

#print(sort_q1_matrix)
sort_q1_matrix_traspose = numpy.transpose(sort_q1_matrix)

print(sort_q1_matrix_traspose)                                  # transpose the original matrix with "sort_q1_matrix_traspose" name


[[0.44363636]
 [0.35454545]
 [0.19636364]
 [0.00545455]]


In [437]:
matrix_1=sort_q1_matrix_traspose.copy()                       # create a new  first duplicate matrix
#print(duplicate)
n= matrix_1[2:,:]
print(n)

g= np.sum(matrix_1[2:,:])                                 # sum of last two row of the first matrix with name "g"
print(g)


[[0.19636364]
 [0.00545455]]
0.2018181818181818


In [438]:
matrix_1[2:,]=g
matrix_1[3:,]=0                                         # replace the values with new one on duplicate matrix
print (matrix_1)

[[0.44363636]
 [0.35454545]
 [0.20181818]
 [0.        ]]


In [439]:
matrix_1=matrix_1[::1]                        
print(matrix_1)                                          # sort a first duplicate matrix

[[0.44363636]
 [0.35454545]
 [0.20181818]
 [0.        ]]


In [440]:
matrix_2=matrix_1.copy()                                       # create a new sedcond duplicate matrix
print (matrix_2)

[[0.44363636]
 [0.35454545]
 [0.20181818]
 [0.        ]]


In [441]:
g2= np.sum(matrix_2[1:,:])                                # sum of the lst two values of the second duplicate matrix 
print(g2)


0.5563636363636364


In [442]:
matrix_2[1:,]=g2                                         # replace the values with new one on second duplicate matrix
matrix_2[2:,]=0
print (matrix_2)

[[0.44363636]
 [0.55636364]
 [0.        ]
 [0.        ]]


In [443]:
matrix_2 = matrix_2[::-1]
print(matrix_2)

[[0.        ]
 [0.        ]
 [0.55636364]
 [0.44363636]]


In [445]:
final_matrix_1= numpy.hstack((sort_q1_matrix_traspose,matrix_1,matrix_2))        # final matrix of qusetion 1
print(final_matrix_1)

[[0.44363636 0.44363636 0.        ]
 [0.35454545 0.35454545 0.        ]
 [0.19636364 0.20181818 0.55636364]
 [0.00545455 0.         0.44363636]]


In [446]:
final_matrix_1[0,2]=final_matrix_1[2,2]
final_matrix_1[1,2]=final_matrix_1[3,2]   
final_matrix_1[2,2]=0   
final_matrix_1[3,2]=0                       # replace the values with new one on duplicate matrix
np.set_printoptions(precision=3)
print (final_matrix_1)

[[0.444 0.444 0.556]
 [0.355 0.355 0.444]
 [0.196 0.202 0.   ]
 [0.005 0.    0.   ]]


In [447]:
mydic= {
   "sub_ur": 0.196, "urban":0.444, "rural": 0.355 ,"other":0.005
}

print(mydic)

{'sub_ur': 0.196, 'urban': 0.444, 'rural': 0.355, 'other': 0.005}


In [448]:
print (sorted(mydic.items()))

[('other', 0.005), ('rural', 0.355), ('sub_ur', 0.196), ('urban', 0.444)]


In [449]:
mydic_sort= (sorted(mydic.items(),key = lambda x : x[1],reverse=True))
print(mydic_sort)

[('urban', 0.444), ('rural', 0.355), ('sub_ur', 0.196), ('other', 0.005)]


In [450]:
matrix_mydic =  [mydic_sort]
print(matrix_mydic)

[[('urban', 0.444), ('rural', 0.355), ('sub_ur', 0.196), ('other', 0.005)]]


In [451]:
matrix_mydic=  numpy.transpose(matrix_mydic)
print(matrix_mydic)


[[['urban']
  ['rural']
  ['sub_ur']
  ['other']]

 [['0.444']
  ['0.355']
  ['0.196']
  ['0.005']]]


In [413]:
class Node:
    def __init__(self, name, p):
        self.left = None
        self.right = None
        self.name = name
        self.p = p
       
    def get_codes(self, h=1, code='', result=None):
        if result == None:
            result = []
        if self.left == None and self.right == None:
            #print (self.name, self.p), code
            result.append((self.name, self.p, code))
        else:
            print (self.name, self.p)
        if self.left != None:
            #print ('    ' * h,)
            self.left.get_codes(h+1, code+'1', result)
        if self.right != None:
            print ('    ' * h,)
            self.right.get_codes(h+1, code+'0', result)
        return result

    def height(self, h=1):
        hl = hr = 1
        if self.left != None:
            hl = self.left.height(h+1)
        if self.right != None:
            hr = self.right.height(h+1)
        return max(h, hl, hr)
    
    def swap(self):
        if self.left == None or self.right == None:
            return
        if self.left.height() > self.right.height():
            self.left, self.right = self.right, self.left
        self.left.swap()
        self.right.swap()

In [414]:
def merge_nodes(nodes):
    if len(nodes) == 1:
        return nodes[0]
    nodes.sort(key=cmp_to_key(lambda x, y: (y.p > x.p) - (y.p < x.p)))
    c1, c2 = nodes.pop(), nodes.pop()
    parent = Node(c1.name + c2.name, c1.p + c2.p)
    parent.left, parent.right = c1, c2
    nodes.append(parent)
    return merge_nodes(nodes)

In [415]:
def huffman(p_list):
    nodes = [Node(chr(ord('a') + c), p)
             for (c, p) in enumerate(p_list)]
    head = merge_nodes(nodes)

   #head.swap()
    result = head.get_codes()

    entropy = 0
    length = 0
    for (name, p, code) in result:
        print (name, p, code)
        entropy += -p * np.log2(p)
        length += p * len(code)
   
    
    
    return result
   

In [416]:
p_list = [0.355,0.444, 0.005, 0.196]
result=huffman(p_list)
print(result)
print(type(result))

bcda 1.0
    
cda 0.556
cd 0.201
            
        
b 0.444 1
c 0.005 011
d 0.196 010
a 0.355 00
[('b', 0.444, '1'), ('c', 0.005, '011'), ('d', 0.196, '010'), ('a', 0.355, '00')]
<class 'list'>


In [417]:

def binaryToDecimal(n): 
    num = n; 
    dec_value = 0; 
      
    # Initializing base  
    # value to 1, i.e 2 ^ 0 
    base1 = 1; 
      
    len1 = len(num); 
    for i in range(len1 - 1, -1, -1): 
        if (num[i] == '1'):      
            dec_value += base1; 
        base1 = base1 * 2; 
      
    return dec_value; 

ak=0
empty_1=[]
list_1= ["URBAN","OTHER","SUB URBAN","RURAL"]
for ankit,gupta, kapil in result:
    
    ankit=list_1[ak] 
    kapil= binaryToDecimal(kapil)
    empty_1.append([ankit,kapil])
    ak+=1
    #print(ankit)



In [418]:
print(result)
print(empty_1)

[('b', 0.444, '1'), ('c', 0.005, '011'), ('d', 0.196, '010'), ('a', 0.355, '00')]
[['URBAN', 1], ['OTHER', 3], ['SUB URBAN', 2], ['RURAL', 0]]
